### DISCUSSION TITLE
怎么使用 docker-compose.yml 进行部署

### DISCUSSION THREAD

**Discussion by Jengro777** [tryzealot/zealot#1355] [Q&A] [answered]
可以提供 一个 docker-compose.yml docker部署文件 吗？ 我只需要修改简单的配置信息， 就可以使用 docker compose up -d 一键部署

**Comment by Jengro777** [comment]
我想部署在 windows 的 docker 上， 可以一键部署

**Comment by icyleaf** [comment, marked as answer]
合并 `https://github.com/tryzealot/zealot-docker/blob/master/templates/docker-compose/base.yml` 和 `https://github.com/tryzealot/zealot-docker/blob/master/templates/docker-compose/local-volumes.yml`

**Comment by Jengro777** [comment]
![image](https://github.com/tryzealot/zealot/assets/35259040/a9f4ec71-97c9-497a-919e-a577d44c2f1a)
部署成功后，访问
![image](https://github.com/tryzealot/zealot/assets/35259040/18e8279d-be42-4cab-a4a6-edcde7346516)
![image](https://github.com/tryzealot/zealot/assets/35259040/b494b472-308b-4793-ab62-9e2606734c0c)

**Reply by Jengro777** [reply]
防火墙 确认是完全关闭的

**Comment by Jengro777** [comment]
![image](https://github.com/tryzealot/zealot/assets/35259040/8bb22d39-6719-4d32-abc3-d83b5207e717)
换成 linux 还是不能访问， 容器已经正常开启了， 防火墙是关闭状态

**Reply by icyleaf** [reply]
linux 环境就用教程步骤一步步安装：https://zealot.ews.im/zh-Hans/docs/self-hosted/deployment/docker

服务需要很多环境变量依赖 zealot-docker 仓库，可以把用脚本生成好的 docker-compose.yml 和 .env 两个文件修改后放到其他平台使用。具体是否能访问是你配置的问题。

**Reply by Jengro777** [reply]
```
######################################
# 域名及证书
######################################

# 语言设置 (默认中文：zh-CN)
# DEFAULT_LOCALE=en

# 网站外观（默认浅色：light）
# ZEALOT_APPEARANCE=dark

# 域名，比如 zealot.com，无需加 http:// 或 https:// 前缀
ZEALOT_DOMAIN=gh.amiemall.com

# Let's Encrypt 注册电子邮箱（和自签名证书文件名二选一，不能同时设置）
# ZEALOT_CERT_EMAIL=

# 自签名证书文件名（和 Let's Encrypt 注册电子邮箱名二选一，不能同时设置）
# ZEALOT_CERT=
# ZEALOT_CERT_KEY=

######################################
# 账户
######################################

# 默认生成的管理员账户和密码
ZEALOT_ADMIN_EMAIL=admin@zealot.com
ZEALOT_ADMIN_PASSWORD=ze@l0t

# 是否开启游客模式 （无需登录即可浏览绝大部分内部服务）
ZEALOT_GUEST_MODE=false

# 是否开放注册功能
ZEALOT_REGISTER_ENABLED=true

######################################
# 第三方一键登录
######################################

## 飞书
# 配置教程：https://zealot.ews.im/docs/self-hosted/configuration/third-party-authentication#feishu-lark
FEISHU_ENABLED=true
FEISHU_APP_ID=
FEISHU_APP_SECRET=

## Gitlab
# 配置教程：https://zealot.ews.im/docs/self-hosted/configuration/third-party-authentication#gitlab
GITLAB_ENABLED=true
GITLAB_SITE=https://gitlab.com/api/v4
GITLAB_SCOPE=read_user
GITLAB_APP_ID=
GITLAB_SECRET=

## Google OAuth
# 配置教程：https://zealot.ews.im/docs/self-hosted/configuration/third-party-authentication#google
GOOGLE_OAUTH_ENABLED=false
GOOGLE_CLIENT_ID=
GOOGLE_SECRET=

## LDAP
# 配置教程：https://zealot.ews.im/docs/self-hosted/configuration/third-party-authentication#ldap
LDAP_ENABLED=false
LDAP_HOST=10.0.0.1
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_BIND_DN="cn=Manager,dc=example,dc=com"
LDAP_PASSWORD=password
LDAP_BASE="ou=People,dc=example,dc=com"
LDAP_UID=uid

######################################
# 发送邮件
######################################

# SMTP
SMTP_ADDRESS=smtp.gmail.com
SMTP_PORT=587
SMTP_DOMAIN=gmail.com
SMTP_USERNAME=you@gmail.com
SMTP_PASSWORD=yourpassword
SMTP_AUTH_METHOD=plain
SMTP_ENABLE_STARTTLS_AUTO=true

# 邮件默认收发人
ACTION_MAILER_DEFAULT_FROM=notifiacation@zealot.com
ACTION_MAILER_DEFAULT_TO=no-reply@zealot.com

######################################
# 定时任务
######################################

# 保留所有上传应用，否则会定期清理上传的应用（调试文件除外）
# 清理规则参见：https://zealot.ews.im/#/configuration
# ZEALOT_KEEP_UPLOADS=true

######################################
# 统计
######################################

# Google Analytics 统计
GOOGLE_ANALYTICS_ID=

# 匿名错误上报
ZEALOT_SENTRY_DISABLE=false

######################################
# 开发使用变量 （非开发者请忽略下面）
######################################

# Docker Compose 项目名（建议保留不变）
COMPOSE_PROJECT_NAME=zealot

# 加密密钥，建议使用 openssl 或者 rails secret 生成
SECRET_TOKEN='gYZa;6Y,wbNRV1)6EaW,3IebqO3<T)38sj)M+mQ34*#Jl,D<lW'

# Puma 外部控制 API
PUMA_CONTROL_URL=0.0.0.0:9293
PUMA_CONTROL_URL_TOKEN=zealot

# The database name will automatically get the Rails environment appended to it
# such as: zealot_development or zealot_production.
ZEALOT_POSTGRES_HOST=postgres
ZEALOT_POSTGRES_PORT=5432
ZEALOT_POSTGRES_USERNAME=postgres
ZEALOT_POSTGRES_PASSWORD=ze@l0t
ZEALOT_POSTGRES_DB_NAME=zealot

# The full Redis URL for the Redis cache.
REDIS_URL=redis://redis:6379/0

```



--------


```
# Generated on Fri Dec  8 16:10:14     2023
# USE SSL: false
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - /opt/zealot_data/uploads:/app/public/uploads
    - /opt/zealot_data/backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - /opt/zealot_data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - /opt/zealot_data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "80:80"
```
