### DISCUSSION TITLE
我用的wsl，我按照教程全部配置好了，但通过127.0.0.1还是无法访问web界面

### DISCUSSION THREAD

**Discussion by hqweb** [tryzealot/zealot#1457] [Q&A] [answered]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

web页面进不去 看不了

### Git 哈希值 (长度 40)| Git Ref (40 length)

web页面进不去 看不了

### 反代服务 | Reverse Proxy

没有

### HTTPS 证书类型 | HTTPS(SSL)

无 none

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

```

version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - zealot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "80:80"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-redis:
    external: true
  zealot-postgres:
    external: true

```

`hq@hq:~/zealot/zealot-docker$ docker container ls
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS                      PORTS                               NAMES
a1337bacdf81   ghcr.io/tryzealot/zealot:nightly   "/init"                  17 minutes ago   Up 12 minutes (unhealthy)   0.0.0.0:80->80/tcp, :::80->80/tcp   a1337bacdf81_zealot_zealot_1
dbdb7a21d37c   redis:7-alpine                     "docker-entrypoint.s…"   17 minutes ago   Up 16 minutes (healthy)     6379/tcp                            zealot_redis_1
9197299216f9   postgres:14-alpine                 "docker-entrypoint.s…"   17 minutes ago   Up 16 minutes (healthy)     5432/tcp                            zealot_postgres_1`

我用127.0.0.1无法访问，用本机的ip 192.168.6.188也无法访问 .

我想换个端口 把- "80:80"  改成 - "9000:80"启动会报错

```
hq@hq:~/zealot/zealot-docker$ docker-compose up -d
zealot_redis_1 is up-to-date
zealot_postgres_1 is up-to-date
Recreating a1337bacdf81_zealot_zealot_1 ...

ERROR: for a1337bacdf81_zealot_zealot_1  'ContainerConfig'

ERROR: for zealot  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[65239] Failed to execute script docker-compose
```

**Comment by icyleaf** [comment]
试试 `docker compose up -d`

**Reply by hqweb** [reply]
```
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - zealot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "9999:80"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-redis:
    external: true
  zealot-postgres:
    external: true
```

docker命令
```
hq@hq:~/zealot/zealot-docker$ docker compose up -d
WARN[0000] /home/hq/zealot/zealot-docker/docker-compose.yml: `version` is obsolete 
[+] Running 3/3
 ✔ Container zealot-postgres-1  Started                                                   0.0s 
 ✔ Container zealot-redis-1     Started                                                   0.0s 
 ✔ Container zealot-zealot-1    Started                                                   2.0s 

hq@hq:~/zealot/zealot-docker$ docker container ls
CONTAINER ID   IMAGE                              COMMAND                  CREATED              STATUS                            PORTS                                   NAMES
2b5495060aa2   ghcr.io/tryzealot/zealot:nightly   "/init"                  9 seconds ago        Up 6 seconds (health: starting)   0.0.0.0:9999->80/tcp, :::9999->80/tcp   zealot-zealot-1
05d78b1bc87d   redis:7-alpine                     "docker-entrypoint.s…"   About a minute ago   Up 7 seconds (health: starting)   6379/tcp                                zealot-redis-1
8e4bfed6c2d5   postgres:14-alpine                 "docker-entrypoint.s…"   About a minute ago   Up 7 seconds (health: starting)   5432/tcp                                zealot-postgres-1
```
使用127.0.0.1:9999访问
<img width="802" alt="1712112663440" src="https://github.com/tryzealot/zealot/assets/27910906/2b0a68f5-b01e-4a63-a215-de5354a3c74a">



### 问题日志 | Relevant log output

_No response_
