### ISSUE TITLE
[Bug]: docker-compose 脚本无法启动

### ISSUE THREAD

**Issue by Mabisi** [tryzealot/zealot#1082]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

nginx

### HTTPS 证书类型 | HTTPS(SSL)

自签名证书 Self-signed SSL

### 已阅读文档 | Read the document

- [x] 已阅读 | Yes

### 描述 | Description

运行docker-compose up -d报错

### 问题日志 | Relevant log output

![image](https://user-images.githubusercontent.com/19968269/222405077-b96b800c-29bb-47b4-90bc-904d17a30a0e.png)

**Comment by icyleaf** [comment]
发下 docker-compose.yml

**Comment by Mabisi** [comment]
> 发下 docker-compose.yml

# Generated on Thu 02 Mar 2023 06:31:26 PM CST
# USE SSL: false
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - zealot-redis:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "9999:80"

volumes:
  zealot-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/app/data/zealot/uploads
  zealot-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/app/data/zealot/backup
  zealot-redis:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/app/data/redis
  zealot-postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/app/data/postgres

**Comment by icyleaf** [comment]
redis 升级版本后忘记改数据路径了，安装下面修改后再试试

```diff
redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
-      - zealot-redis:/var/lib/redis/data
+      - zealot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
```

**Comment by Mabisi** [comment]
> 

![image](https://user-images.githubusercontent.com/19968269/222650297-88ad8314-b6f8-4f15-946b-84fbe6a3fd52.png)

重新拉去修改了还是不行。。

**Comment by icyleaf** [comment]
看来新版本使用这种 bind 挂载本地路径不太好了，改成这样吧：

```yaml
# Generated on Thu 02 Mar 2023 06:31:26 PM CST
# USE SSL: false
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - /opt/app/data/zealot/uploads:/app/public/uploads
    - /opt/app/data/zealot/backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - /opt/app/data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - /opt/app/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "9999:80"
```
