### ISSUE TITLE
[Bug]: 使用k8s部署，80端口无法访问

### ISSUE THREAD

**Issue by nothinggift** [tryzealot/zealot#1120]
### 部署方式 | How to Deploy

Kubernates

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

caddy

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

k8s部署文档上有一些拼写错误，但部署正常，下面容器日志看起来也很正常，但无论直接访问端口，还是域名都无法访问，容器日志没有看到任何报错

### 问题日志 | Relevant log output

```shell
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 11-crontab-dir: applying... 
[fix-attrs.d] 11-crontab-dir: exited 1.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 11-set-crontab: executing... 
[cont-init.d] 11-set-crontab: exited 0.
[cont-init.d] 12-logrotate: executing... 
[cont-init.d] 12-logrotate: exited 0.
[cont-init.d] 20-init-zealot: executing... 
[cont-init.d] 20-init-zealot: exited 0.
[cont-init.d] 21-fix-caddy-format: executing... 
[cont-init.d] 21-fix-caddy-format: exited 0.
[cont-init.d] 25-upgrade-zealot: executing... 
Zealot upgrade database ...
[cont-init.d] 25-upgrade-zealot: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Zealot Worker
Starting Caddy
Starting Zealot
[services.d] done.
[349] Puma starting in cluster mode...
[349] * Puma version: 6.2.0 (ruby 3.0.6-p216) ("Speaking of Now")
[349] *  Min threads: 5
[349] *  Max threads: 5
[349] *  Environment: production
[349] *   Master PID: 349
[349] *      Workers: 2
[349] *     Restarts: (✔) hot (✔) phased
[349] * Listening on http://127.0.0.1:3000
[349] Use Ctrl-C to stop
[349] * Starting control server on http://127.0.0.1:9293
2023-04-06T07:48:31.939Z pid=344 tid=mi8 INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"internal", :url=>"redis://localhost:6379/1"}
2023-04-06T07:48:31.957Z pid=344 tid=mi8 INFO: SidekiqScheduler is disabled
[349] - Worker 0 (PID: 378) booted in 2.8s, phase: 0
2023-04-06T07:48:33.063Z pid=344 tid=mi8 INFO: Booted Rails 7.0.4.3 application in production environment
2023-04-06T07:48:33.063Z pid=344 tid=mi8 INFO: Running in ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux-musl]
2023-04-06T07:48:33.063Z pid=344 tid=mi8 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-04-06T07:48:33.063Z pid=344 tid=mi8 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2023-04-06T07:48:33.064Z pid=344 tid=mi8 INFO: Sidekiq 7.0.8 connecting to Redis with options {:size=>5, :pool_name=>"default", :url=>"redis://localhost:6379/1"}
2023-04-06T07:48:33.066Z pid=344 tid=mi8 INFO: Loading Schedule
2023-04-06T07:48:33.066Z pid=344 tid=mi8 INFO: Scheduling sync_apple_devices {"cron"=>"0 0 * * *", "class"=>"SyncAppleDevicesJob", "queue"=>"schedule", "description"=>"Syncing devices for all Apple Developers on each 0AM"}
2023-04-06T07:48:33.069Z pid=344 tid=mi8 INFO: Schedules Loaded
[349] - Worker 1 (PID: 380) booted in 2.83s, phase: 0
```

**Comment by icyleaf** [comment]
服务已经正常跑起来，服务对外暴露的是 80 端口。文档 deploymnet.yml 漏了几个端口的配置：

```diff
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zealot
  namespace: zealot
spec:
  restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: zealot
  template:
    metadata:
      labels:
        app: zealot
    spec:
      containers:
        - name: zealot
          image: ghcr.io/tryzealot/zealot:nightly
          # imagePullPolicy: Always
          ports:
            - containerPort: 80
+             protocol: TCP
+             name: http
          envFrom:
            - configMapRef:
              name: zealot-env
            - secretKeyRef:
              name: zealot-secrets
          volumeMounts:
            - mountPath: /app/public/uploads
              name: uploads
            - mountPath: /app/public/backup
              name: backup
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: zealot-uploads
        - name: backup
          persistentVolumeClaim:
            claimName: zealot-backup
```

"k8s部署文档上有一些拼写错误" 麻烦可以帮忙指出一下吗？

**Comment by nothinggift** [comment]
没问题了，确实缺了name

30-zealot-storage.yml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zealot-uploads
+ namespace: zealot
  labels:
    app: zealot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zealot-backup
+ namespace: zealot
  labels:
    app: zealot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
40-zealot-deployment.yml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zealot
  namespace: zealot
spec:
  restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: zealot
  template:
    metadata:
      labels:
        app: zealot
    spec:
      containers:
        - name: zealot
          image: ghcr.io/tryzealot/zealot:nightly
          # imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
              name: zealot-env
-          - secretKeyRef:
+          - secretRef:
              name: zealot-secrets
          volumeMounts:
            - mountPath: /app/public/uploads
              name: uploads
            - mountPath: /app/public/backup
              name: backup
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: zealot-uploads
        - name: backup
          persistentVolumeClaim:
            claimName: zealot-backup
```
