### ISSUE TITLE
[Bug]: 添加开发者接口报错 500

### ISSUE THREAD

**Issue by HolmesZhao** [tryzealot/zealot#1261]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

nightly (Default)

### 反代服务 | Reverse Proxy

none

### HTTPS 证书类型 | HTTPS(SSL)

可受信任的证书 Verified SSL

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

5.0.0-nightly版本, domain 使用的是阿里云签的免费 SSL, 文件改成自签名的文件名称, domain 解析到本地 ip, 进入后台管理, 上传 app 安装 app 都没问题, 就是添加开发者的接口报错, 下面带上请求的 curl, host 和关键的 🆔 信息已经消除

### 问题日志 | Relevant log output

```shell
curl 'https://xx.xxxx.press/admin/apple_keys' \
  -H 'authority: xx.xxxx.press' \
  -H 'accept: text/vnd.turbo-stream.html, text/html, application/xhtml+xml' \
  -H 'accept-language: zh-CN,zh;q=0.9' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryg3FBvDEzHjC9CR6l' \
  -H 'cookie: SRCHUSR=T=1685005295000; ABDEF=V=13&ABDV=13&MRB=1686120547450&MRNB=0; _ga=GA1.2.1553150622.1686798048; SRCHHPGUSR=BRW=XW&BRH=M&CW=1496&CH=796&SCW=1496&SCH=796&DPR=1.0&UTC=480&DM=1&PRVCW=1496&PRVCH=796&cdxtone=Balanced&cdxtoneopts=harmonyv3; _gid=GA1.2.380277197.1693461249; _ga_WT651ZYM85=GS1.2.1693464189.3.0.1693464189.0.0.0; _zealot_session=c6uSB6w0Qj7jUbvYIaj2YWps1l2rX6UwG6zrx1hr%2F9Zr%2Ffq1619PE%2FILEmgF7%2BvxEY1RHQB2SmW1tRZDh7x2Nryamqxk4C%2BRX2ytxOqc4JHJnIQddRO08hWjgHqrcC9kto04RH%2F5WtyrUCVfxRAf%2FGxgytmQbJjBF9U9F9ei8cGo1LgmeO1R0VfXiCSG4shIoR7K71V7ot0MP9j0V9%2BJ9AH6KmPIfpkLxuuLfaQ4GoC2lpY1N%2BsMbYeCr6m9%2FB3BH%2F%2F9s1o2riJiVJGnz8Xrt0sJJOBclVPEHWJmkVfgjJjxt%2BIE6YI%2Bd8uc77cXUuJSg13hEDHf3u1T%2FKt%2FZesLsPk0xn%2FnhU0UhShws%2BzJmged3QmZ6syeTk1BPbzYjrrvPuNGixQ1GQ%3D%3D--e3IStT5crS2ni5Ki--u%2FMWiJNQksPL4HUumGIrMQ%3D%3D' \
  -H 'origin: https://xxx.xxxx.press' \
  -H 'referer: https://xxx.xxxx.press/admin/apple_keys/new' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  -H 'x-csrf-token: CZEmalsapSrTiOMJ0mBYsGwW7GvETPNvh7Lo8FTfU1etW496wiE1QLPeltxpBsqDlgHLcjGl1Fsu1SxLRpFRQA' \
  -H 'x-forwarded-for: 1.64.33.87' \
  --data-raw $'------WebKitFormBoundaryg3FBvDEzHjC9CR6l\r\nContent-Disposition: form-data; name="authenticity_token"\r\n\r\nGhUOMzAzdrfIAUgyOw3R-RVJXNF7zXKMGa1q2HasK31E6EoKbD2kr4P_LarOVysWTCys0YquhMJvgbrs-7TWww\r\n------WebKitFormBoundaryg3FBvDEzHjC9CR6l\r\nContent-Disposition: form-data; name="apple_key[issuer_id]"\r\n\r\n801e2b2f-xxx-4756-ae53-xxx7c919\r\n------WebKitFormBoundaryg3FBvDEzHjC9CR6l\r\nContent-Disposition: form-data; name="apple_key[key_id]"\r\n\r\nQ69xxxx68\r\n------WebKitFormBoundaryg3FBvDEzHjC9CR6l\r\nContent-Disposition: form-data; name="apple_key[private_key]"; filename="AuthKey_Q6xxxxx68.p8"\r\nContent-Type: application/octet-stream\r\n\r\n\r\n------WebKitFormBoundaryg3FBvDEzHjC9CR6l\r\nContent-Disposition: form-data; name="commit"\r\n\r\n新增苹果开发者\r\n------WebKitFormBoundaryg3FBvDEzHjC9CR6l--\r\n' \
  --compressed
```

**Comment by icyleaf** [comment]
请问创建的苹果开发者时在服务器端没有创建 distribution 的证书？

**Comment by HolmesZhao** [comment]
> 请问创建的苹果开发者时在服务器端没有创建 distribution 的证书？

没有😂只有 dev 的证书, 回头试试看

**Comment by HolmesZhao** [comment]
![image](https://github.com/tryzealot/zealot/assets/19728934/b917267c-7462-4d9f-bc76-1a5e2380b93d)
我现在执行 upgrade 后服务跑不起来了, 报 503 错误, 启动 zealot 报错日志如下

```
[2162] ! Unable to start worker
[2162] (<unknown>): did not find expected comment or line break while scanning a block scalar at line 14 column 20
[2162] /usr/local/lib/ruby/3.0.0/psych.rb:457:in `parse'
    /usr/local/lib/ruby/3.0.0/psych.rb:457:in `parse_stream'
    /usr/local/lib/ruby/3.0.0/psych.rb:391:in `parse'
    /usr/local/lib/ruby/3.0.0/psych.rb:280:in `unsafe_load'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/secrets.rb:30:in `block in parse'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/secrets.rb:26:in `each'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/secrets.rb:26:in `each_with_object'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/secrets.rb:26:in `parse'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/application.rb:394:in `secrets'
    /app/vendor/bundle/ruby/3.0.0/gems/devise-4.9.2/lib/devise/secret_key_finder.rb:12:in `find'
    /app/vendor/bundle/ruby/3.0.0/gems/devise-4.9.2/lib/devise/rails.rb:37:in `block in <class:Engine>'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `instance_exec'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:32:in `run'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
    /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
    /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
    /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
    /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
    /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
    /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/initializable.rb:60:in `run_initializers'
    /app/vendor/bundle/ruby/3.0.0/gems/railties-7.0.7.2/lib/rails/application.rb:372:in `initialize!'
    /app/config/environment.rb:7:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block in <main>'
    /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
    /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
    /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
    /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/configuration.rb:366:in `load_rackup'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/configuration.rb:288:in `app'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/runner.rb:169:in `app'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/runner.rb:173:in `start_server'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster/worker.rb:60:in `run'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:206:in `worker'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:99:in `block in spawn_worker'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:99:in `fork'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:99:in `spawn_worker'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:81:in `block in spawn_workers'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:74:in `times'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:74:in `spawn_workers'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:163:in `check_workers'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cluster.rb:436:in `run'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/launcher.rb:194:in `run'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/lib/puma/cli.rb:75:in `run'
    /app/vendor/bundle/ruby/3.0.0/gems/puma-6.3.1/bin/puma:10:in `<top (required)>'
    ./bin/puma:29:in `load'
    ./bin/puma:29:in `<main>'
[2162] Early termination of worker
```

**Comment by icyleaf** [comment]
服务代码内部不需要手动执行任何更新操作的，等待 https://github.com/tryzealot/zealot/actions/runs/6045043528 跑完后重新拉取 `nightly` tag 重启服务即可。

**Comment by HolmesZhao** [comment]
> 服务代码内部不需要手动执行任何更新操作的，等待 https://github.com/tryzealot/zealot/actions/runs/6045043528 跑完后重新拉取 `nightly` tag 重启服务即可。

好的等 run 完, 稍后我卸载重新尝试一下, 感谢~

**Comment by HolmesZhao** [comment]
> > 服务代码内部不需要手动执行任何更新操作的，等待 https://github.com/tryzealot/zealot/actions/runs/6045043528 跑完后重新拉取 `nightly` tag 重启服务即可。
> 
> 好的等 run 完, 稍后我卸载重新尝试一下, 感谢~

不行啊, 已经是最新的了还是报错

这个是 image : 
![image](https://github.com/tryzealot/zealot/assets/19728934/3f83ca62-b1c6-4e06-a8a3-b112c8027396)

这个是`docker-compose.yml`:
```yml
# Generated on 2023年 8月31日 星期四 21时49分21秒 CST
# USE SSL: self-signed
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - zealot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
  web:
    image: caddy:2-alpine
    ports:
      - "1180:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro
    env_file: .env
    environment:
      ACME_AGREE: "true"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-redis:
    external: true
  zealot-postgres:
    external: true
```
