### ISSUE TITLE
[Bug]: 通过docker compose up -d启动成功，但是用127.0.0.1或本机ip无法访问

### ISSUE THREAD

**Issue by hqweb** [tryzealot/zealot#1460]
### 部署方式 | How to Deploy

使用一键部署脚本 | Using zealot-docker on-click install (Default)

### 部署版本 | Version

无法进入

### Git 哈希值 (长度 40)| Git Ref (40 length)

无法进入

### 反代服务 | Reverse Proxy

无

### HTTPS 证书类型 | HTTPS(SSL)

无 none

### 已阅读文档 | Read the document

- [X] 已阅读 | Yes

### 描述 | Description

```
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:nightly
  depends_on:
    - redis
    - postgres
  env_file: .env
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  redis:
    <<: *restart_policy
    image: redis:7-alpine
    command: redis-server
    volumes:
      - zealot-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ze@l0t
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
    ports:
      - "9999:80"

volumes:
  zealot-uploads:
    external: true
  zealot-backup:
    external: true
  zealot-redis:
    external: true
  zealot-postgres:
    external: true
```

docker命令
```
hq@hq:~/zealot/zealot-docker$ docker compose up -d
WARN[0000] /home/hq/zealot/zealot-docker/docker-compose.yml: `version` is obsolete 
[+] Running 3/3
 ✔ Container zealot-postgres-1  Started                                                   0.0s 
 ✔ Container zealot-redis-1     Started                                                   0.0s 
 ✔ Container zealot-zealot-1    Started                                                   2.0s 

hq@hq:~/zealot/zealot-docker$ docker container ls
CONTAINER ID   IMAGE                              COMMAND                  CREATED              STATUS                            PORTS                                   NAMES
2b5495060aa2   ghcr.io/tryzealot/zealot:nightly   "/init"                  9 seconds ago        Up 6 seconds (health: starting)   0.0.0.0:9999->80/tcp, :::9999->80/tcp   zealot-zealot-1
05d78b1bc87d   redis:7-alpine                     "docker-entrypoint.s…"   About a minute ago   Up 7 seconds (health: starting)   6379/tcp                                zealot-redis-1
8e4bfed6c2d5   postgres:14-alpine                 "docker-entrypoint.s…"   About a minute ago   Up 7 seconds (health: starting)   5432/tcp                                zealot-postgres-1
```
使用127.0.0.1:9999访问
<img width="802" alt="1712112663440" src="https://github.com/tryzealot/zealot/assets/27910906/2b0a68f5-b01e-4a63-a215-de5354a3c74a">
