### ISSUE TITLE
problems about ldap

### ISSUE THREAD

**Issue by Martwu** [tryzealot/zealot#541]
我使用docker部署，开了ldap，现在ldap登陆，会返回错误：

Not found. Authentication passthru.

我应该如何排查？

**Comment by icyleaf** [comment]
其实 LDAP 我一直不是特别熟悉，更多的错误信息看下 `/app/log/zealot.log` 里面如果找到麻烦发一下，我尝试看看是啥问题

**Comment by icyleaf** [comment]
找到问题所在了，迁移 rails-settings-cached 的时候变量没有两边匹配上

**Comment by icyleaf** [comment]
等 [![Publish Nightly Docker Image](https://github.com/tryzealot/zealot/actions/workflows/publish_nighty.yml/badge.svg?branch=develop)](https://github.com/tryzealot/zealot/actions/workflows/publish_nighty.yml) 这个跑完重新拉下版本再试试

**Comment by icyleaf** [comment]
给自己备注一个 ldap 的测试脚本：

```yaml
version: '3'

services:
  ldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: 123456
    ports:
      - "389:389"
      - "636:636"
  ui:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "8080:80"
```
