### ISSUE TITLE
caddy 可能会要求确认

### ISSUE THREAD

**Issue by ReverseScale** [tryzealot/zealot#551]
![image](https://user-images.githubusercontent.com/13606492/129653696-49ca39aa-1829-4189-b712-e4fb83c7930a.png)

可以在 docker run 上加个参数
`-e ACME_AGREE=true \`

**Comment by icyleaf** [comment]
请问这个会在什么情况下遇到？

**Comment by ReverseScale** [comment]
多谢回复哈，
我是使用 Let's Encrypt SSL 证书方式部署，拉的这个 Commit（refactor: 使用 gcr.io 作为 zealot 的镜像源），docker 运行后 caddy 起不来，就是一直要求确认。

网上查到可以这样解决：
https://github.com/abiosoft/caddy-docker/issues/102
我再试着改一下 docker-compose.yml
```
  web:
    container_name: zealot-web
    image: abiosoft/caddy:0.10.12 
    ports:
      - "80:80"
      - "443:443"
    environment:
      ACME_AGREE: "true"
    volumes:
      - ./rootfs/etc/Caddyfile:/etc/Caddyfile
      - ./rootfs/etc/certs:/etc/certs
      - ./zealot-data:/app/public
    env_file: .env
```
